package server;

public enum Request {
	CREATEUSERACCOUNT("CREATEUSERACCOUNT"),
	LOGIN("LOGIN"),
	LOGOUT("LOGOUT"),
	CREATEGROUP("CREATEGROUP"),
	GETUSERBYNAME("GETUSERBYNAME"),
	GETUSERBYUSERID("GETUSERBYUSERID"),
	INVITEUSERTOGROUP("INVITEUSERTOGROUP"),
	GETGROUPINFO("GETGROUPINFO"),
	SETGROUPSETTING("SETGROUPSETTING"),
	REMOVEUSER("REMOVEUSER"),
	ENTERTRANSACTION("ENTERTRANSACTION"),
	ADDBUDGET("ADDBUDGET"),
	SETPERSONALSETTING("SETPERSONALSETTING"),
	NOTIFICATIONRESPONSE("NOTIFICATIONRESPONSE"),
	REQUESTNOTIFICATIONS("REQUESTNOTIFICATIONS"),
	VIEWTRANSACTIONS("VIEWTRANSACTIONS"),
	GETSTATUS("GETSTATUS");

	final String string;
	Request(String string) {
		this.string = string;
	}
}
